import type { ViewState } from "./controller";
import type { FactoryGraph, GraphChange } from "./domain";

const esc = (value: string | number): string => String(value).replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);
const disabled = (condition: boolean) => condition ? " disabled" : "";
export function renderGraph(state: ViewState): string {
  const graph = state.graph;
  if (!graph) return `<section class="detail-card graph-section"><h2>Task graph</h2><p>Inspect task dependencies, proof and execution preferences.</p><button class="button" type="button" data-action="graph"${disabled(!state.connected || !!state.pending || state.graphLoading)}>${state.graphLoading ? "Reading graph…" : "Open task graph"}</button></section>`;
  const selected = graph.nodes.find(node => node.id === state.selectedNodeId);
  const locked = !state.connected || !!state.pending || state.graphStale || state.graphLoading || !graph.planning_only && (graph.claim.held || graph.claim.status !== "released");
  const nodeLocked = locked || selected?.admission !== "candidate" || !!selected.owner_thread || !!selected.attempt_ids.length;
  const proposal = state.proposal;
  const eligible = state.backends?.targets.filter(target => target.operator_enabled && target.planning_eligible && target.qualification !== "unsupported") ?? [];
  return `<section class="graph-section" aria-label="Task graph">
    <div class="section-heading"><h2>Task graph</h2><button class="button" type="button" data-action="graph"${disabled(!!state.pending || state.graphLoading || !state.connected)}>${state.graphLoading ? "Reading…" : "Refresh graph"}</button></div>
    <p class="graph-caption">${graph.planning_only ? "Planning only · Execution has not been authorized" : "Persisted task and attempt history"} · Revision ${graph.revision} · Claim ${esc(graph.claim.status)}</p>
    ${state.graphStale ? '<div class="notice error" role="status">This graph may be stale. Its last valid view is preserved; refresh before changing it.</div>' : ""}
    <div class="graph-layout"><div class="graph-nodes" aria-label="Tasks and dependencies">${graph.nodes.map(node => `<button type="button" id="node-${esc(node.id)}" class="graph-node${node.id === state.selectedNodeId ? " selected" : ""}" data-action="graph-node" data-node-id="${esc(node.id)}" aria-pressed="${node.id === state.selectedNodeId}"><span class="graph-node-status">${esc(node.state)} · ${esc(node.admission)}</span><strong>${esc(node.title)}</strong><span class="mono">${esc(node.id)}</span><span>${node.dependencies.length ? `Depends on ${node.dependencies.map(id => esc(graph.nodes.find(item => item.id === id)?.title ?? id)).join(", ")} → this task` : "No prerequisites"}</span><span>${node.criterion_ids.length} criteria · ${node.attempt_ids.length} attempts</span></button>`).join("") || '<div class="empty empty-card"><h3>No tasks yet</h3><p>Import candidates through the factory change tools to build this plan.</p></div>'}</div>
    <aside class="graph-inspector detail-card" aria-label="Selected task inspector">${selected ? `<div class="eyebrow">SELECTED TASK</div><h3>${esc(selected.title)}</h3><dl class="route-list"><dt>Task ID</dt><dd>${esc(selected.id)}</dd><dt>State</dt><dd>${esc(selected.state)} · ${esc(selected.admission)}</dd><dt>Owner</dt><dd>${esc(selected.owner_thread ?? "No owner assigned")}</dd><dt>Reason</dt><dd>${esc(selected.reason ?? "No blocker reported")}</dd><dt>Preference</dt><dd>${esc(selected.target_preference ?? "Not selected")}</dd></dl>
      <h4>Acceptance and proof</h4><ul class="graph-proof">${selected.criterion_ids.map(id => { const criterion = graph.criteria.find(item => item.id === id); return `<li><strong>${esc(criterion?.status ?? "unverified")}</strong> · ${esc(criterion?.description ?? id)}${criterion?.check_refs.length ? `<small>Checks: ${criterion.check_refs.map(esc).join(", ")}</small>` : ""}</li>`; }).join("") || "<li>No criterion bindings.</li>"}</ul>
      ${selected.source ? `<details id="source-${esc(selected.id)}"><summary>Imported source</summary><dl class="route-list"><dt>Provider</dt><dd>${esc(selected.source.provider)}</dd><dt>Item</dt><dd>${esc(selected.source.item_id)}</dd><dt>Revision</dt><dd>${esc(selected.source.revision)}</dd><dt>Repository</dt><dd class="mono">${esc(selected.source.repository_id)}</dd></dl></details>` : ""}
      <details id="attempts-${esc(selected.id)}"><summary>Attempt history · ${selected.attempt_ids.length}</summary>${graph.attempts.filter(attempt => attempt.task_id === selected.id).map(attempt => `<p class="small">${esc(attempt.id)} · ${esc(attempt.status)}<br>Thread ${esc(attempt.thread_id ?? "unknown")} · Turn ${esc(attempt.turn_id ?? "unknown")}<br><span class="mono">${esc(attempt.subject)}</span></p>`).join("") || '<p class="small muted">No execution attempts recorded.</p>'}</details>
      <details id="edit-${esc(selected.id)}" class="planning-editor"><summary>Edit this candidate plan</summary><p class="field-hint">Selecting a task only inspects it. Saving a proposal records a review draft. Only an explicitly confirmed application changes the plan; no work is dispatched.</p><form data-form="graph-node" data-input-identity="${esc(graph.run_id)}:${esc(selected.id)}:${graph.revision}">
        ${nodeLocked && !locked ? '<p class="field-hint">Only candidate tasks with no execution history can be edited.</p>' : ""}
        <div class="field"><label for="dependencies">Prerequisite tasks</label><select id="dependencies" name="dependencies" multiple size="${Math.min(5, Math.max(2, graph.nodes.length - 1))}"${disabled(nodeLocked)}>${graph.nodes.filter(node => node.id !== selected.id).map(node => `<option value="${esc(node.id)}"${selected.dependencies.includes(node.id) ? " selected" : ""}>${esc(node.title)}</option>`).join("")}</select><p class="field-hint">Choose the tasks that must finish first. ${selected.dependencies.length ? "Clearing all selections proposes removal of existing prerequisites." : "There are no prerequisites yet. Empty selection leaves the plan unchanged."} The server rejects cycles.</p></div><button class="button" type="submit" value="dependencies"${disabled(nodeLocked)}>Save prerequisite proposal</button>
        <details id="target-${esc(selected.id)}" class="target-editor"><summary>Optional planning target note</summary><div class="field target-field"><label for="target_id">Planning target note</label><select id="target_id" name="target_id"${disabled(nodeLocked || !eligible.length)}><option value=""${selected.target_preference === null ? " selected" : ""}>No preference</option>${eligible.map(target => `<option value="${esc(target.id)}"${selected.target_preference === target.id ? " selected" : ""}${disabled(!target.planning_eligible)}>${esc(target.label)} · execution unverified</option>`).join("") || '<option value="">Read targets with Refresh graph</option>'}</select><p class="field-hint">A planning preference does not authorize execution or verify subscription access.</p></div><button class="button" type="submit" value="target"${disabled(nodeLocked || !eligible.length)}>Save planning note proposal</button></details>
      </form></details>` : '<p class="muted">Select a task to inspect its proof and configure the plan.</p>'}</aside></div>
    ${proposal ? `<section class="detail-card graph-review" aria-label="Review graph change"><div class="eyebrow">${proposal.status === "applied" ? "APPLIED CHANGE" : "REVIEW BEFORE APPLYING"}</div><h3>${esc(changeTitle(proposal.change))}</h3><p>${esc(changeDescription(proposal.change, graph))}</p><details id="change-audit-${esc(proposal.id)}"><summary>Change identity and revision</summary><p class="small muted">Base revision ${proposal.base_revision} · ${esc(proposal.id)}<br>Subject <span class="mono">${esc(proposal.subject)}</span></p></details>${proposal.status === "proposed" ? `<label class="change-confirmation"><input id="confirm-graph-change" type="checkbox" data-confirm-identity="${esc(proposal.id)}:${graph.revision}"${disabled(locked || proposal.base_revision + 1 !== graph.revision)}> I confirm this exact plan change at revision ${graph.revision}.</label><button id="apply-graph-change" class="button primary" type="button" data-action="apply-change" disabled>Apply confirmed plan change</button><p class="small muted">Records this exact change to the plan. No work is dispatched.</p>` : `<p class="small">Applied at revision ${proposal.applied_revision ?? "unknown"}.</p>`}</section>` : ""}
    <details id="execution-targets" class="detail-card advanced"><summary>Execution targets and qualification</summary><p class="small">Configuration discovery only. Subscription entitlement and execution are unverified unless independently qualified.</p>${state.backends?.targets.map(target => `<article class="ledger-row"><strong>${esc(target.label)}</strong><span>${target.execution_eligible ? "Execution eligible" : "Execution unavailable"}</span><p>${esc(target.reason)} · ${esc(target.qualification)}<br>Authentication ${esc(target.authentication)} · Entitlement ${esc(target.entitlement)}</p></article>`).join("") || '<p class="muted">Target catalog is unavailable. Refresh the graph to read it.</p>'}</details>
  </section>`;
}
function changeTitle(change: GraphChange): string {
  return change.kind === "set_target" ? "Change execution preference" : change.kind === "set_dependencies" ? "Change prerequisite tasks" : "Import candidate tasks";
}
function changeDescription(change: GraphChange, graph: FactoryGraph): string {
  if (change.kind === "set_target") return `${change.node_id}: prefer ${change.target_id}.`;
  if (change.kind === "set_dependencies") return `${change.node_id}: current prerequisites ${graph.nodes.find(node => node.id === change.node_id)?.dependencies.join(", ") || "none"}; proposed prerequisites ${change.dependencies.join(", ") || "none"}.`;
  return `${change.nodes.length} candidates: ${change.nodes.map(node => node.title).join(", ")}.`;
}
