import { allowedFinishes, classifyRun, finishLabels, runPath, type RunView } from "./domain";
import type { ViewState } from "./controller";

export type Editor = "start" | "settings" | "steer" | "stop" | null;
const escape = (value: string | number): string => String(value).replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c] ?? c);
const icon = (name: "moon" | "plus" | "arrow" | "refresh" | "settings" | "close") => {
  const paths = { moon: '<path d="M17.4 13.3A7 7 0 0 1 6.7 2.6 7.5 7.5 0 1 0 17.4 13.3Z"/>', plus: '<path d="M10 4v12M4 10h12"/>', arrow: '<path d="m7 5 5 5-5 5"/>', refresh: '<path d="M16 7a6.3 6.3 0 1 0 .3 5M16 3v4h-4"/>', settings: '<path d="M4 6h12M4 14h12M7 3v6M13 11v6"/>', close: '<path d="m5 5 10 10M15 5 5 15"/>' };
  return `<svg viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]}</svg>`;
};
const stateLabel = (run: RunView): string => run.state.toLowerCase().replaceAll("_", " ");
const badge = (run: RunView): string => `<span class="badge ${classifyRun(run)}"><span></span>${escape(stateLabel(run))}</span>`;
const disabled = (value: boolean): string => value ? " disabled" : "";
const button = (action: string, label: string, options: { primary?: boolean; disabled?: boolean; icon?: "plus" | "refresh" | "settings" | "close" } = {}): string => `<button type="button" data-action="${action}" class="button${options.primary ? " primary" : ""}"${disabled(options.disabled ?? false)}>${options.icon ? icon(options.icon) : ""}${escape(label)}</button>`;

export function renderWorkbench(root: HTMLElement, state: ViewState, editor: Editor, preview: boolean): void {
  const oldForm = root.querySelector<HTMLFormElement>("form");
  const oldKind = oldForm?.dataset.form;
  const draft = oldForm ? new FormData(oldForm) : null;
  const active = document.activeElement;
  const focusId = active instanceof HTMLElement && root.contains(active) ? active.id : null;
  const selection = active instanceof HTMLTextAreaElement ? [active.selectionStart, active.selectionEnd] : null;
  const expanded = Array.from(root.querySelectorAll<HTMLDetailsElement>("details[open]")).map(element => element.id);
  const run = state.runs.find(item => item.id === state.selectedId);
  const canStart = Boolean(state.connected && state.capabilities?.repositories.length && state.capabilities.profiles.length && !state.pending);
  const needs = state.runs.filter(item => classifyRun(item) === "needs").length;
  const activeCount = state.runs.filter(item => classifyRun(item) === "active").length;
  root.innerHTML = `<div class="workbench">
    ${preview ? '<div class="preview-banner">Fixture visual preview · Synthetic run data · No live integration</div>' : ""}
    <header class="topbar"><a class="brand" href="/" data-action="overview"><span class="brand-mark">${icon("moon")}</span><span>Luna Factory<span class="brand-sub">WORKBENCH</span></span></a><div class="top-actions"><span class="connection"><i class="${state.connected ? "online" : ""}"></i>${state.connected ? "Connected" : "Connecting"}</span>${button("settings", "Defaults", { icon: "settings", disabled: !state.capabilities || Boolean(state.pending) })}${button("start", "New run", { primary: true, icon: "plus", disabled: !canStart })}</div></header>
    <div class="layout"><aside class="sidebar" aria-label="Factory runs"><div class="sidebar-heading"><button class="overview-button" type="button" data-action="overview">All runs <span>${state.runs.length}</span></button><button class="icon-button" type="button" data-action="refresh" aria-label="Refresh runs"${disabled(!state.connected || state.refreshing || Boolean(state.pending))}>${icon("refresh")}</button></div>
      ${([ ["needs", "Needs me"], ["active", "Active"], ["recent", "Recent"] ] as const).map(([group, label]) => {
        const runs = state.runs.filter(item => classifyRun(item) === group);
        return `<section class="run-group"><h2>${label}<span>${runs.length}</span></h2>${runs.length ? runs.map(item => `<a class="run-nav ${state.selectedId === item.id ? "selected" : ""}" href="${runPath(item.id)}" data-run-id="${escape(item.id)}"${state.selectedId === item.id ? ' aria-current="page"' : ""}><div class="nav-repository">${escape(item.repository)}<span class="state-dot ${group}" title="${escape(stateLabel(item))}"></span></div><div class="nav-objective">${escape(item.objective)}</div><p>${escape(group === "needs" ? item.blocker || item.remaining_gap || stateLabel(item) : item.delta)}</p></a>`).join("") : `<p class="group-empty">${group === "needs" ? "Nothing needs your attention" : group === "active" ? "No work in progress" : "Completed runs appear here"}</p>`}</section>`;
      }).join("")}
      <div class="sidebar-note"><span class="tiny-moon">${icon("moon")}</span><p>One owner. Bounded work.<br>Evidence before completion.</p></div>
    </aside><main id="main" class="main">
      <div class="status-area" aria-live="polite" aria-atomic="true">${state.pending ? `<div class="notice pending"><span class="spinner"></span>${state.pending.tool === "cancel_factory_run" ? "Stopping owned execution. Waiting for verified status…" : "Waiting for the server…"}</div>` : state.refreshing ? '<div class="quiet-status">Refreshing persisted state…</div>' : ""}${state.notice ? `<div class="notice success">${escape(state.notice)}</div>` : ""}${state.error ? `<div class="notice error" role="alert">${escape(state.error)}${button("refresh", "Refresh", { disabled: !state.connected || Boolean(state.pending) })}</div>` : ""}${state.contextError ? `<div class="notice">${escape(state.contextError)}</div>` : ""}</div>
      ${editor ? renderEditor(editor, state, run) : !state.initialized ? '<section class="empty welcome"><span class="large-moon">' + icon("moon") + '</span><h1>Opening your factory</h1><p>Waiting for the host’s initial run data.</p><p class="muted">Open Luna Factory from your MCP Apps host to connect.</p></section>' : state.selectedId ? run ? renderRun(run, state) : '<section class="empty"><h1>Opening this run</h1><p>The exact run is being read from the server.</p></section>' : renderOverview(state, needs, activeCount, canStart)}
      <footer class="footer">${state.refreshing ? "Reading current state" : "Status reads use no inference"}<span>Native Codex execution</span></footer>
    </main></div></div>`;
  const newForm = root.querySelector<HTMLFormElement>("form");
  if (draft && newForm && oldKind === newForm.dataset.form && oldForm?.dataset.inputIdentity === newForm.dataset.inputIdentity) {
    for (const field of newForm.querySelectorAll<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>("input[name],textarea[name],select[name]")) {
      const value = draft.get(field.name);
      if (typeof value === "string") field.value = value;
    }
  }
  for (const id of expanded) { const element = document.getElementById(id); if (element instanceof HTMLDetailsElement && root.contains(element)) element.open = true; }
  if (focusId) {
    const element = root.querySelector<HTMLElement>(`[id="${escape(focusId)}"]`);
    element?.focus({ preventScroll: true });
    if (element instanceof HTMLTextAreaElement && selection?.[0] !== undefined && selection[1] !== undefined) element.setSelectionRange(selection[0], selection[1]);
  }
}

function renderOverview(state: ViewState, needs: number, active: number, canStart: boolean): string {
  const featured = state.runs.filter(run => classifyRun(run) === "needs");
  const others = state.runs.filter(run => classifyRun(run) !== "needs");
  return `<section class="page-heading"><span class="eyebrow">YOUR WORK, IN MOTION</span><h1>A little attention.<br>A lot of progress.</h1><p>See what changed, what remains, and where you’re needed.</p></section>
    <div class="summary-grid"><div class="summary-card attention"><span>Needs me</span><strong>${needs.toString().padStart(2, "0")}</strong><small>${needs ? "A decision or blocker to resolve" : "You’re clear for now"}</small></div><div class="summary-card"><span>Active runs</span><strong>${active.toString().padStart(2, "0")}</strong><small>Owned, bounded work in progress</small></div><div class="summary-card"><span>Recent outcomes</span><strong>${state.runs.filter(run => classifyRun(run) === "recent").length.toString().padStart(2, "0")}</strong><small>History stays with each run</small></div></div>
    ${!state.capabilities?.repositories.length ? '<div class="notice">No repositories configured. An operator must register trusted aliases on the local server before a run can start.</div>' : ""}
    ${state.runs.length ? `<section class="activity-section"><div class="section-heading"><h2>${featured.length ? "Your next decision" : "Latest changes"}</h2><span>Delta first</span></div>${[...featured, ...others].slice(0, 8).map(run => `<a class="activity-card" href="${runPath(run.id)}" data-run-id="${escape(run.id)}"><div class="activity-top"><span class="repo-label">${escape(run.repository)}</span>${badge(run)}</div><h3>${escape(run.objective)}</h3><p class="delta">${escape(run.delta)}</p><div class="activity-bottom"><span>${escape(run.blocker || run.remaining_gap || "No remaining gap reported")}</span>${icon("arrow")}</div></a>`).join("")}</section>` : `<section class="empty empty-card"><span class="large-moon">${icon("moon")}</span><h2>No runs yet</h2><p>Give Luna one objective and a clear finish line.<br>Its progress and evidence will stay here.</p>${button("start", "Start your first run", { primary: true, icon: "plus", disabled: !canStart })}</section>`}`;
}

function renderRun(run: RunView, state: ViewState): string {
  const busy = !state.connected || Boolean(state.pending);
  const resumable = ["BLOCKED", "QUIESCENT", "INTERRUPTED", "FAILED", "CANCELLED"].includes(run.state);
  const steerable = Boolean(run.pending_decision) || Boolean(run.turn_id) && ["RUNNING", "VERIFYING"].includes(run.state);
  const stoppable = run.claim_held && run.state !== "CANCELLING" && !["CANCELLED", "CONVERGED"].includes(run.state);
  return `<nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/" data-action="overview">Factory</a>${icon("arrow")}<span>${escape(run.repository)}</span></nav><section class="run-heading"><div class="run-title-row"><span class="repo-label">${escape(run.repository)}</span>${badge(run)}</div><h1>${escape(run.objective)}</h1><div class="run-meta"><span>${run.active_workers} / ${run.capacity} workers</span><span>${escape(finishLabels[run.finish])}</span><span>${escape(run.profile)} profile</span></div></section>
    <section class="delta-panel"><div class="eyebrow"><span class="live-dot"></span>What changed</div><p>${escape(run.delta || "No new delta reported")}</p><div class="remaining"><span>Still needed</span><p>${escape(run.remaining_gap || "No mandatory gap reported")}</p></div></section>
    ${run.blocker || run.pending_decision ? `<section class="decision-panel"><div class="eyebrow">${run.pending_decision ? "One decision needs you" : "Needs attention"}</div><h2>${escape(run.pending_decision?.question || run.blocker || "")}</h2><p>${steerable ? "Your answer goes to the same owner. The run keeps its existing authority and limits." : "Resolve the blocker in the native owner environment, then resume this same run when it is safe."}</p></section>` : ""}
    <div class="run-controls">${steerable ? button("steer", run.pending_decision ? "Answer the owner" : "Steer run", { primary: true, disabled: busy }) : ""}${resumable ? button("resume", "Resume same run", { primary: true, disabled: busy }) : ""}${stoppable ? button("stop", "Stop run", { disabled: busy }) : ""}<a class="run-link" href="${runPath(run.id)}" data-run-id="${escape(run.id)}">Exact run ${icon("arrow")}</a></div>
    <div class="detail-grid"><section class="detail-card"><div class="section-heading"><h2>Acceptance</h2><span>${run.acceptance.length} mandatory</span></div><ol class="acceptance-list">${run.acceptance.map((criterion, index) => `<li><span>A${index + 1}</span><p>${escape(criterion)}</p></li>`).join("")}</ol><p class="muted small">Criteria are the finish line. Evidence and owner acceptance determine the outcome.</p>${run.non_goals.length ? `<details id="non-goals"><summary>Outside this run</summary><ul>${run.non_goals.map(goal => `<li>${escape(goal)}</li>`).join("")}</ul></details>` : ""}</section><section class="detail-card"><div class="section-heading"><h2>Model route</h2><span>Reported by runtime</span></div><dl class="route-list"><dt>Requested</dt><dd>${escape(run.route.requested_model || "Not reported")}<small>${escape(run.route.requested_effort || "Effort not reported")}</small></dd><dt>Configured</dt><dd>${escape(run.route.configured_model || "Not reported")}<small>${escape(run.route.configured_effort || "Effort not reported")}</small></dd><dt>Observed</dt><dd>${escape(run.route.observed_model || "No execution-side model evidence")}<small>${escape(run.route.observed_effort || "Effort telemetry unavailable")}</small>${run.route.observed_model_source ? `<small>Source: ${escape(run.route.observed_model_source)}, current owner turn</small>` : ""}</dd><dt>Provider</dt><dd>${escape(run.route.configured_provider || "Configuration not reported")}<small>Inherited configuration; downstream execution and billing unverified</small></dd></dl>${run.route.reroutes?.length ? `<div class="notice error">${run.route.reroutes.length} native model mismatch${run.route.reroutes.length === 1 ? "" : "es"} recorded. ${run.route.reroutes.map(route => `${escape(route.from_model)} → ${escape(route.to_model)} (${escape(route.thread_id)}, ${escape(route.turn_id)})`).join("; ")}</div>` : ""}<p class="muted small">Configured routing is not execution proof. No reroute notification does not prove a matching model.</p></section></div>
    <section class="detail-card evidence-card"><div class="section-heading"><h2>Evidence</h2><span>${run.receipts.length} recent receipts</span></div>${run.receipts.length ? run.receipts.map((receipt, index) => `<details class="receipt" id="receipt-${escape(run.id)}-${index}"><summary><span class="receipt-dot"></span><span><strong>${escape(receipt.kind.replaceAll("_", " "))}</strong><span class="receipt-summary">${escape(receipt.summary)}</span></span><time datetime="${new Date(receipt.created_at * 1000).toISOString()}">${new Date(receipt.created_at * 1000).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</time></summary><div class="receipt-body"><p>${escape(receipt.summary)}</p><dl><dt>Exact subject</dt><dd class="mono">${escape(receipt.subject)}</dd><dt>Freshness</dt><dd>${receipt.subject === run.current_subject ? "Matches the current subject" : "Different subject; re-verification may be needed"}</dd></dl></div></details>`).join("") : '<p class="muted">No execution receipts yet. A running state alone is not evidence.</p>'}</section>
    <details id="run-identity" class="identity"><summary>Run identity &amp; ownership <span>${run.claim_held ? "Repository claim held" : "Repository claim released"}</span></summary><dl><dt>Run</dt><dd class="mono">${escape(run.id)}</dd><dt>Current subject</dt><dd class="mono">${escape(run.current_subject)}</dd><dt>Owner thread</dt><dd class="mono">${escape(run.owner_thread || "Not started")}</dd><dt>Current turn</dt><dd class="mono">${escape(run.turn_id || "None active")}</dd><dt>Deadline</dt><dd>${new Date(run.deadline_at * 1000).toLocaleString()}</dd></dl></details>`;
}

const field = (name: string, label: string, control: string, hint = ""): string => `<div class="field"><label for="${name}">${label}</label>${control}${hint ? `<p class="field-hint" id="${name}-hint">${hint}</p>` : ""}</div>`;
function renderEditor(editor: Exclude<Editor, null>, state: ViewState, run: RunView | undefined): string {
  const title = { start: "Start a bounded run", settings: "Factory defaults", steer: run?.pending_decision ? "Answer the owner" : "Steer this run", stop: "Stop this run?" }[editor];
  const locked = !state.connected || Boolean(state.pending);
  const header = `<div class="editor-heading"><div><span class="eyebrow">${editor === "start" ? "A CLEAR FINISH LINE" : "LUNA FACTORY"}</span><h1>${title}</h1></div>${button("close-editor", "Close", { icon: "close", disabled: Boolean(state.pending) })}</div>`;
  if (editor === "steer" || editor === "stop") {
    if (!run) return `${header}<p>Select a run first.</p>`;
    if (editor === "stop") return `${header}<section class="editor-card"><p class="lead">${escape(run.objective)}</p><p>The server interrupts the owned execution and checks its descendants before releasing the repository claim. Unknown survivors leave the run blocked.</p><p>The objective, evidence, and history stay with this run. A later resume keeps its original authority and remaining limits.</p><form data-form="stop"><div class="form-actions"><button class="button danger" type="submit"${disabled(locked)}>Stop owned execution</button>${button("close-editor", "Keep running", { disabled: Boolean(state.pending) })}</div></form></section>`;
    return `${header}<section class="editor-card">${run.pending_decision || run.blocker ? `<div class="decision-quote">${escape(run.pending_decision?.question || run.blocker || "")}</div>` : `<p>Send a correction to the current owner of <strong>${escape(run.repository)}</strong>.</p>`}<form data-form="steer" data-input-identity="${escape(run.pending_decision?.id || run.turn_id || run.id)}">${field("message", "Your answer or correction", '<textarea id="message" name="message" rows="6" required maxlength="4000" placeholder="What should the owner do differently?" aria-describedby="message-hint"></textarea>', run.pending_decision ? "Continues the same run and owner thread with your answer. Existing limits stay in place. Security approvals must be handled in native Codex." : "Sent to the current turn only. This cannot expand permissions or approve a security prompt.")}<div class="form-actions"><button class="button primary" type="submit"${disabled(locked || !run.pending_decision && !run.turn_id)}>Send to owner</button><span>Existing scope and finish authority stay in place</span></div></form></section>`;
  }
  const cap = state.capabilities;
  if (!cap || !cap.repositories.length || !cap.profiles.length) return `${header}<div class="notice">No approved repository and profile combination is available. Check the trusted server configuration.</div>`;
  const repository = cap.repositories[0];
  if (!repository) return header;
  const profileOptions = cap.profiles.map(profile => `<option value="${escape(profile.alias)}"${profile.alias === state.settings.profile ? " selected" : ""}>${escape(profile.alias)} · ${escape(profile.effort)}</option>`).join("");
  const finishes = editor === "settings" ? allowedFinishes("pr") : allowedFinishes(repository.max_finish);
  const finishOptions = finishes.map(finish => `<option value="${finish}"${finish === state.settings.finish ? " selected" : ""}>${finishLabels[finish]}</option>`).join("");
  return `${header}<section class="editor-card"><p class="editor-intro">${editor === "start" ? "One objective, one durable owner. Choose the bounds before work begins." : "Safe defaults for new runs. These do not change repository access, provider settings, or trusted limits."}</p><form data-form="${editor}">
    ${editor === "start" ? field("repository", "Approved repository", `<select id="repository" name="repository" required>${cap.repositories.map(repo => `<option value="${escape(repo.alias)}">${escape(repo.alias)}</option>`).join("")}</select>`) + field("objective", "Objective", '<textarea id="objective" name="objective" rows="3" required maxlength="8000" placeholder="What should be true when this run finishes?"></textarea>') + field("acceptance", "Mandatory acceptance", '<textarea id="acceptance" name="acceptance" rows="3" required maxlength="32032" placeholder="One verifiable criterion per line" aria-describedby="acceptance-hint"></textarea>', "One criterion per line, up to 32. The owner must verify these against the exact subject.") + field("non_goals", "Non-goals", '<textarea id="non_goals" name="non_goals" rows="2" maxlength="32032" placeholder="What should this run leave alone?" aria-describedby="non_goals-hint"></textarea>', "Optional, one per line") : ""}
    <div class="form-grid">${field("finish", "Finish authority", `<select id="finish" name="finish">${finishOptions}</select>`)}${field("profile", "Approved runtime profile", `<select id="profile" name="profile">${profileOptions}</select>`)}</div>
    ${field("capacity", "Worker capacity", `<input id="capacity" name="capacity" type="number" min="1" max="${cap.limits.capacity}" step="1" value="${Math.min(state.settings.capacity || 1, cap.limits.capacity)}" required aria-describedby="capacity-hint">`, `At most ${cap.limits.capacity} concurrent workers`)}
    ${editor === "start" ? `<details id="run-budgets" class="budget-details"><summary>Time &amp; repair budget</summary><div class="form-grid">${field("wall_seconds", "Time limit, seconds", `<input id="wall_seconds" name="wall_seconds" type="number" min="30" max="${cap.limits.wall_seconds}" step="1" value="${Math.min(1800, cap.limits.wall_seconds)}" required>`)}${field("repair_attempts", "Repair attempts", `<input id="repair_attempts" name="repair_attempts" type="number" min="0" max="${cap.limits.repair_attempts}" step="1" value="${Math.min(2, cap.limits.repair_attempts)}" required>`)}</div></details><div class="authority-note">${icon("moon")}<p>The server validates every action. No merge, release, or deployment is granted by this form.</p></div>` : ""}
    <div class="form-actions"><button class="button primary" type="submit"${disabled(locked)}>${editor === "start" ? "Start run" : "Save defaults"}</button><span>${editor === "start" ? "Starts native Codex execution" : "Applies to future runs"}</span></div></form></section>`;
}
